#!/usr/bin/env bash
#
# Plug-n-play setup for the Mac Controller server.
# Idempotent + non-destructive: re-running it never clobbers an existing
# .env, venv, or certificates — it only fills in what's missing.
#
# Usage:
#   ./setup.sh
#   WEB_APP_URL=https://my.app MAX_DEVICES=3 ./setup.sh   # override defaults
#
set -euo pipefail

# ---- configurable (override via env) ----
WEB_APP_URL="${WEB_APP_URL:-https://mac-remote.gaurangnandaniya.com}"
MAX_DEVICES="${MAX_DEVICES:-5}"

cd "$(dirname "$0")"

say()  { printf "\033[1;36m==>\033[0m %s\n" "$1"; }
ok()   { printf "\033[1;32m  ✓\033[0m %s\n" "$1"; }
warn() { printf "\033[1;33m  !\033[0m %s\n" "$1"; }
die()  { printf "\033[1;31m  ✗ %s\033[0m\n" "$1" >&2; exit 1; }

[ "$(uname)" = "Darwin" ] || die "This server runs on macOS only."
command -v python3 >/dev/null 2>&1 || die "python3 not found — install it (e.g. from python.org or 'brew install python')."
command -v brew >/dev/null 2>&1 || die "Homebrew not found — install it from https://brew.sh then re-run."
ok "macOS, python3, and Homebrew present"

# ---- 1. system dependencies ----
say "Checking system dependencies (mkcert, nss, portaudio)"
for pkg in mkcert nss portaudio; do
  if brew list "$pkg" >/dev/null 2>&1; then
    ok "$pkg already installed"
  else
    say "Installing $pkg via Homebrew"
    brew install "$pkg"
  fi
done

# mkcert local certificate authority (idempotent; may prompt for your password)
if [ -f "$(mkcert -CAROOT 2>/dev/null)/rootCA.pem" ]; then
  ok "mkcert local CA already installed"
else
  say "Installing mkcert local CA (you may be prompted for your password)"
  mkcert -install
fi

# ---- 2. python virtualenv + dependencies ----
if [ -d venv ]; then
  ok "venv already exists"
else
  say "Creating Python virtualenv"
  python3 -m venv venv
  ok "venv created"
fi
say "Installing Python dependencies (this can take a few minutes the first time)"
./venv/bin/pip install --quiet --upgrade pip
./venv/bin/pip install --quiet -r requirements.txt
ok "Python dependencies installed"

# ---- 3. TLS certificates ----
if [ -f cert.pem ] && [ -f key.pem ]; then
  ok "TLS certs (cert.pem/key.pem) already exist — skipping"
else
  # Match the name the server advertises: socket.gethostname() + ".local"
  HOST_RAW="$(./venv/bin/python3 -c 'import socket; print(socket.gethostname())')"
  case "$HOST_RAW" in
    *.local) LOCAL_NAME="$HOST_RAW" ;;
    *)       LOCAL_NAME="$HOST_RAW.local" ;;
  esac
  LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
  say "Generating TLS cert for: $LOCAL_NAME localhost 127.0.0.1 ::1 ${LAN_IP:-(no LAN IP found)}"
  # Fixed output names so .env paths are deterministic.
  mkcert -cert-file cert.pem -key-file key.pem "$LOCAL_NAME" localhost 127.0.0.1 ::1 ${LAN_IP:+$LAN_IP}
  ok "Wrote cert.pem + key.pem (covers $LOCAL_NAME)"
fi

# ---- 4. .env ----
if [ -f .env ]; then
  ok ".env already exists — leaving it untouched"
else
  say "Writing .env"
  SECRET="$(./venv/bin/python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
  cat > .env <<ENV
# Generated by setup.sh
AUTH_SECRET_KEY=$SECRET
MAX_DEVICES=$MAX_DEVICES
WEB_APP_URL=$WEB_APP_URL
CERTIFICATE_PATH=./cert.pem
PRIVATE_KEY_PATH=./key.pem
ENV
  ok ".env created (random AUTH_SECRET_KEY, WEB_APP_URL=$WEB_APP_URL)"
fi

# ---- done ----
CAROOT="$(mkcert -CAROOT 2>/dev/null || echo '<run: mkcert -CAROOT>')"
printf "\n\033[1;32mSetup complete.\033[0m\n\n"
cat <<DONE
Next steps:
  1. Trust the mkcert root CA on your iPhone (one-time, needed for HTTPS):
       • rootCA.pem is here:  $CAROOT/rootCA.pem
       • AirDrop it to the iPhone, then install the profile
       • Settings → General → About → Certificate Trust Settings → turn on Full Trust for "mkcert …"
  2. Start the server:
       source venv/bin/activate && python3 mac_controller_app.py
  3. Open the menu-bar QR and scan it from the web app to pair.
DONE
